apiVersion: api.sandatasystem.com/v1
kind: Notebook
metadata:
  name: notebook-sample
spec:
  # TODO(user): Add fields here
  template:
    spec:
      containers:
        - name: notebook-sample-v1
          image: kubeflownotebookswg/jupyter:v1.5.0-rc.1

  user: "abc"
  project: "def"
  canAccess:
  - '2313'
  - '2141'
  
