apiVersion: api.sandatasystem.com/v1
kind: Notebook
metadata:
  name: notebook-sample
spec:
  # TODO(user): Add fields here
  template:
    spec:
      containers:
        - name: notebook-sample-v1
          image: public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter:v1.5.0
  user: "abc"
  project: "def"
  access:
  - '2313'
  - '2141'
  
